## Default profile settings

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.26'
remappings = [
    'forge-std/=lib/forge-std/src/',
    'v4-core/=lib/v4-core/contracts/',
    'v4-periphery/=lib/v4-periphery/contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'
]
# Explicitly disable forking
eth_rpc_url = ''

# Test configuration
fuzz = { runs = 256 }
# No fork URL for default testing

## Perfil para pruebas sin validaciones de hooks

[profile.simple_test]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 800
# Saltarse las validaciones de hooks para tests
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.sepolia]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.26'
evm_version = 'cancun'
fuzz = { runs = 256 }
invariant = { runs = 256 }
fork_url = "https://sepolia.base.org"